# Generated by Django 4.1.7 on 2023-02-20 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='short_content',
            field=models.CharField(default=4, max_length=500),
            preserve_default=False,
        ),
    ]
