# Generated by Django 4.1.7 on 2023-02-20 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_post_short_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(help_text='cum o sa apara in URL', max_length=200, unique=True),
        ),
    ]
