# Generated by Django 4.1.7 on 2023-02-21 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_alter_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default=4, upload_to='images/'),
            preserve_default=False,
        ),
    ]
